### ISSUE TITLE
menu not showing correctly on mobile

### ISSUE THREAD

**Issue by treynola** [mor10/popper#11]
Thank you the Popper theme is awesome!

On mobile browser the page has to be resized for menu to show up on the home page.

**Comment by bueltge** [comment]
@treynola In different tests works this fine for me. The menu is always on the bottom left, like in this screenshot below. Please test again. Maybe use a other browser for testing.
![auswahl_001](https://cloud.githubusercontent.com/assets/133425/21013073/f0e33458-bd58-11e6-81e7-21caf0740452.png)

**Comment by Zodiac1978** [comment]
@treynola I can't reproduce this too. Without more information in which devices this occurs we can't fix it.
