### ISSUE TITLE
Close?

### ISSUE THREAD

**Issue by Zodiac1978** [mor10/popper#52]
There is no traction here for 4 years now. Krautpress has moved to another theme and bueltge.de also. I don't use the theme anywhere, so nobody works on it anymore. The theme on wp.org was never moved to me from Morten (https://wordpress.org/themes/popper/) and there are only ca. 100 user left.

I don't see any future for this theme if nobody uses it and has some intrinsic motivation to work on it.

So let's close/archive it.

**Comment by bueltge** [comment]
Yes, same oppinion for me. We should archive then, not delete.

**Comment by bueltge** [comment]
I do it.
