### ISSUE TITLE
Menu button hidden on Android browser

### ISSUE THREAD

**Issue by ckschmieder** [mor10/popper#6]
The Android browser has a navigation menu across the bottom that shows/hides in the same way as your menu button and is therefore always covering it. 

Discovered while working with popperscores and confirmed it by visiting your site mor10.com using Android Browser (Samsung Galaxy S5).

**Comment by giorgioriccardi** [comment]
The problem is in the settings of that basic browser. 
Go into settings and deselect Auto hide toolbar.
I'll send screenshots later.
Hope it helps

**Comment by ckschmieder** [comment]
Good call.. that works.  Thanks.
